version: '3.4'

services:
  gripopgras2.server:
    image: ${DOCKER_REGISTRY-}gripopgras2server
    build:
      context: .
      dockerfile: GripOpGras2.Server/Dockerfile
    container_name: gripopgras2.server
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:4200
    ports:
      - "4200:4200"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  prometheus:
    image: prom/prometheus:v2.41.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    
volumes:
  grafana-storage:
  prometheus_data: