global:
  scrape_interval:     10s
  evaluation_interval:  5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: blazorwebassemblyprometheus.server 
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:4200