name: Delete Pull Request Deployment
on:
  pull_request:
    branches: 
    - main
    types: [ closed ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  PR_REPO_NAME: GripOpGras2.0-pr-${{ github.event.pull_request.node_id }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository for temporary deployment
        uses: octobay/delete-repository-action@v1
        with:
          name: GripOpGras/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.GRIPOPGRAS_PAT }}
