name: Deploy github pages


# Run workflow on every push to the master branch
on:
  push:
    branches:
      - main
      
jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:

    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v2

    # sets up .NET Core SDK 6.0.x
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        

      # Install dotnet wasm buildtools workload
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools

      # Publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish GripOpGras2.0.sln -c:Release -p:GHPages=true -o dist/Web --nologo

      #Deploy pages to gh-pages branch
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist/Web/wwwroot
        token: ${{secrets.GITHUB_TOKEN}}
        
