name: Trigger auto deployment for gripopgras2server-app-2022120617

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'GripOpGras2.Server/**'
    - 'GripOpGras2.Client/**'
    - '.github/workflows/gripopgras2server-app-2022120617-AutoDeployTrigger-d8ae62b6-4bfb-432d-ba8a-5ad62d81d087.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com/gripopgras
          username: ${{ secrets.GRIPOPGRAS2SERVERAPP2022120617_REGISTRY_USERNAME }}
          password: ${{ secrets.GRIPOPGRAS2SERVERAPP2022120617_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            registry.hub.docker.com/gripopgras/gripopgras2server-app-2022120617:${{ github.sha }}
            registry.hub.docker.com/gripopgras/gripopgras2server-app-2022120617:latest
          file: GripOpGras2.Server/Dockerfile
          context: .


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GRIPOPGRAS2SERVERAPP2022120617_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n gripopgras2server-app-2022120617 -g gripopgras2server-app-2022120617ResourceGroup --server registry.hub.docker.com/gripopgras --username  ${{ secrets.GRIPOPGRAS2SERVERAPP2022120617_REGISTRY_USERNAME }} --password ${{ secrets.GRIPOPGRAS2SERVERAPP2022120617_REGISTRY_PASSWORD }}
            az containerapp update -n gripopgras2server-app-2022120617 -g gripopgras2server-app-2022120617ResourceGroup --image registry.hub.docker.com/gripopgras/gripopgras2server-app-2022120617:${{ github.sha }}
